Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.StreamLambdaHandler
      CodeUri: C:\Users\Isabella\password-api-lambda-itau\HelloWorldFunction
      Runtime: java21
      Architectures:
        - x86_64